package UI;

import Backend.Logica;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author jara
 */
public class JFInterfaz extends javax.swing.JFrame {
    //Se declaran las variables que seran usadas en la clase
    ImagenFondo iF = new ImagenFondo();
    Logica lc = new Logica();
    String txt1, txt2;
    /**
     * Creates new form JFInterfaz
     */
    public JFInterfaz() {
        this.setContentPane(iF);
        this.setTitle("Decodificador ADN");
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JTextField();
        lbl2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Laboratorio de Biologia");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 300, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ingrese la primera cadena de ADN:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 220, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingrese la segunda cadena de ADN:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 220, -1));
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 300, -1));
        jPanel1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 300, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 80, 40));

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 90, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Se obtienen los valores que ingresaron y se guardan en Strings
    //Se le manda los parametros a los metodos que estan en la clase Logica para ejecutarse el buscador
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    txt1 = lbl1.getText().trim();
    txt2 = lbl2.getText().trim();
    lc.cadena1(txt1);
    lc.cadena2(txt2);
    lc.buscador();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    //Despues de encontrar la cadena se setean los valores iniciales para que puedan seguir ingresando
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        lbl1.setText("");
        lbl2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lbl1;
    private javax.swing.JTextField lbl2;
    // End of variables declaration//GEN-END:variables

    //Esta clase es propia de Java y sirve para poner un fondo de pantalla
    class ImagenFondo extends JPanel {
        private Image imagen;

        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/adn.jpg")).getImage();
            g.drawImage(imagen,0 , 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    
}
